import { PredictorTool } from './types';

export const TOOLS: PredictorTool[] = [
  {
    id: 'crop-yield-pred',
    title: 'Crop Yield Predictor',
    description: 'Estimate expected yield based on soil conditions, weather patterns, and historical data.',
    category: 'Crop prediction',
    predictionType: 'Volume Estimate',
    horizon: '1-6 Months',
    confidence: 'High',
    featured: true,
    newest: false,
    mostUsed: true,
    inputsUsed: ['Historical Yield Data', 'Current Weather Forecast', 'Soil Moisture Sensors', 'Fertilizer Application Rates'],
    predictionOutput: 'Estimated Bushels per Acre with an 80% confidence band.',
    modelExplanation: 'Uses a Random Forest regression model trained on 20 years of regional agricultural data, adjusted dynamically by current season weather indices.',
    assumptions: ['Assumes standard harvesting practices will be followed.', 'No catastrophic weather events (e.g., severe hail, hurricane) before harvest.'],
    relatedToolIds: ['weather-impact-pred', 'harvest-timing-pred'],
  },
  {
    id: 'cattle-weight-pred',
    title: 'Cattle Weight Predictor',
    description: 'Forecast livestock weight gain curves to optimize feed and market timing.',
    category: 'Livestock prediction',
    predictionType: 'Growth Curve',
    horizon: '3-12 Months',
    confidence: 'Medium',
    featured: true,
    newest: false,
    mostUsed: false,
    inputsUsed: ['Breed Type', 'Initial Weight', 'Feed Ration Composition', 'Average Temperature Trends'],
    predictionOutput: 'Projected weight trajectory over the specified horizon.',
    modelExplanation: 'Based on standard physiological growth curves adjusted by feed energy values and thermal stress impacts.',
    assumptions: ['Animals remain healthy and disease-free.', 'Consistent feed quality.'],
    relatedToolIds: ['feed-req-pred', 'price-risk-pred'],
  },
  {
    id: 'input-demand-pred',
    title: 'Input Demand Predictor',
    description: 'Predict fertilizer and seed demand driven by regional planting intentions.',
    category: 'Input demand prediction',
    predictionType: 'Market Demand',
    horizon: '3-6 Months',
    confidence: 'Medium',
    featured: false,
    newest: true,
    mostUsed: false,
    inputsUsed: ['Regional Planting Intentions', 'Commodity Price Futures', 'Historical Usage Rates'],
    predictionOutput: 'Expected tonnage of NPK fertilizer required by region.',
    modelExplanation: 'Aggregates micro-economic planting decisions based on futures pricing to forecast aggregate input needs.',
    assumptions: ['No sudden supply chain disruptions.', 'Farmers adhere to stated planting intentions.'],
    relatedToolIds: ['price-risk-pred'],
  },
  {
    id: 'price-risk-pred',
    title: 'Price Risk Predictor',
    description: 'Assess the probability of commodity price drops below break-even thresholds.',
    category: 'Price movement prediction',
    predictionType: 'Probability Analysis',
    horizon: '1-3 Months',
    confidence: 'Low',
    featured: false,
    newest: false,
    mostUsed: true,
    inputsUsed: ['Current Futures Prices', 'Market Volatility Index', 'Global Supply Reports'],
    predictionOutput: 'Percentage probability of price falling below the user-defined break-even point.',
    modelExplanation: 'Employs Monte Carlo simulations based on historical volatility and current market options pricing.',
    assumptions: ['Markets remain rational.', 'No major geopolitical shocks during the prediction window.'],
    relatedToolIds: ['crop-yield-pred'],
  },
  {
    id: 'pest-outbreak-pred',
    title: 'Pest Outbreak Predictor',
    description: 'Identify high-risk periods for pest infestations based on thermal models.',
    category: 'Disease / pest risk prediction',
    predictionType: 'Risk Timeline',
    horizon: '2-4 Weeks',
    confidence: 'High',
    featured: true,
    newest: true,
    mostUsed: false,
    inputsUsed: ['Cumulative Degree Days (CDD)', 'Crop Phenology', 'Historical Outbreak Data'],
    predictionOutput: 'Heatmap timeline indicating high, medium, and low risk days for specific pests.',
    modelExplanation: 'Uses biological degree-day models to predict the lifecycle stages of common agricultural pests.',
    assumptions: ['Local temperature data accurately reflects field conditions.', 'No preventative spraying has occurred yet.'],
    relatedToolIds: ['disease-risk-pred'],
  },
  {
    id: 'disease-risk-pred',
    title: 'Disease Risk Predictor',
    description: 'Evaluate probability of fungal infections based on leaf wetness and humidity.',
    category: 'Disease / pest risk prediction',
    predictionType: 'Risk Index',
    horizon: '1-2 Weeks',
    confidence: 'Medium',
    featured: false,
    newest: false,
    mostUsed: false,
    inputsUsed: ['Relative Humidity', 'Leaf Wetness Hours', 'Temperature Extremes'],
    predictionOutput: 'A daily risk index score from 0-100 indicating conditions favorable for disease development.',
    modelExplanation: 'Empirical model correlating environmental factors with historical disease incidence rates.',
    assumptions: ['Susceptible crop varieties are planted.', 'Pathogen inoculum is present in the environment.'],
    relatedToolIds: ['pest-outbreak-pred', 'weather-impact-pred'],
  },
  {
    id: 'feed-req-pred',
    title: 'Feed Requirement Predictor',
    description: 'Calculate future feed tonnage needed to reach target weights.',
    category: 'Livestock prediction',
    predictionType: 'Volume Estimate',
    horizon: '1-6 Months',
    confidence: 'High',
    featured: false,
    newest: false,
    mostUsed: false,
    inputsUsed: ['Target Market Weight', 'Current Herd Size', 'Average Daily Gain (ADG)'],
    predictionOutput: 'Total dry matter intake required, categorized by feed type.',
    modelExplanation: 'A deterministic model utilizing standard nutritional requirements combined with herd demographics.',
    assumptions: ['Feed formulation remains constant.', 'Zero significant herd loss.'],
    relatedToolIds: ['cattle-weight-pred'],
  },
  {
    id: 'harvest-timing-pred',
    title: 'Harvest Timing Predictor',
    description: 'Optimize harvest dates based on crop maturity and weather forecasts.',
    category: 'Weather-linked prediction',
    predictionType: 'Date Optimization',
    horizon: '1-4 Weeks',
    confidence: 'Medium',
    featured: false,
    newest: true,
    mostUsed: true,
    inputsUsed: ['Planting Date', 'Growing Degree Days (GDD)', '14-Day Weather Forecast'],
    predictionOutput: 'Recommended optimal 3-day harvest window.',
    modelExplanation: 'Combines physiological maturity models with weather risk penalty functions to maximize workable field hours.',
    assumptions: ['Equipment is available and operational.', 'Crop maturity is consistent across the field.'],
    relatedToolIds: ['crop-yield-pred'],
  }
];
